### ISSUE TITLE
Improve typesense search results

### ISSUE THREAD

**Issue by TheoWolf** [databrary/databrary.org#147]
The search result is not accurate and needs to be improved.

┆Issue is synchronized with this [Trello card](https://trello.com/c/m2NoVvCv) by [Unito](https://www.unito.io/learn-more)

**Comment by jasonbosco** [comment]
@TheoWolf 👋 I'm one of the authors of Typesense. I just stumbled on this issue on Github and thought I'd let you know that we just released an update (v0.18.0) that addresses some issues with multi-field queries: https://github.com/typesense/typesense/releases/tag/v0.18.0

Could you give it a shot and let me know if you still see the same issues? I'd love to work with you to identify any remaining issues.

**Comment by TheoWolf** [comment]
@jasonbosco Thanks for the heads up, I upgraded to 0.19 and the multi-field queries seem to perform better.
Note: You have breaking changes not mentioned in your docs; the field type object is not supported anymore and 'boolean' is now 'bool', I felt that is important to mention.
Thanks for this awesome tool.

**Comment by jasonbosco** [comment]
Hi @TheoWolf, we've always had the data-typed named as `bool` and we didn't have `object` as a data-type since we don't support nested fields. 

What we did add recently was validation to make sure that the data-type specified in the schema was actually a valid one. I'm guessing that's what you might have run into - if you were using `boolean` and `object` previously, those were just ignored silently (which was a gotcha). In a recent version we added an explicit validation, which would cause it to error out.
